pipeline:
  build:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker --tls=false info
      - docker --tls=false build -t build-lazarus-armhf .